// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace OnlineShop.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260918073020_CodiceOrdineGestionePrenotazioni")]
    partial class CodiceOrdineGestionePrenotazioni
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.Carrello", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("TEXT");

                    b.Property<int>("UtenteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UtenteId");

                    b.ToTable("Carrelli");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.CarrelloProdotto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarrelloId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProdottoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantita")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CarrelloId");

                    b.HasIndex("ProdottoId");

                    b.ToTable("CarrelloProdotti");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.CarrelloProdottoOpzione", b =>
                {
                    b.Property<int>("CarrelloProdottoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OpzioneProdottoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Sovrapprezzo")
                        .HasColumnType("TEXT");

                    b.HasKey("CarrelloProdottoId", "OpzioneProdottoId");

                    b.HasIndex("OpzioneProdottoId");

                    b.ToTable("CarrelliProdottiOpzioni");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.DettaglioProdotto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Certificazione")
                        .HasColumnType("TEXT");

                    b.Property<string>("Colore")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descrizione")
                        .HasColumnType("TEXT");

                    b.Property<string>("Garanzia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Marca")
                        .HasColumnType("TEXT");

                    b.Property<string>("Materiale")
                        .HasColumnType("TEXT");

                    b.Property<string>("Misura")
                        .HasColumnType("TEXT");

                    b.Property<string>("Modello")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("Peso")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProdottoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProdottoId")
                        .IsUnique();

                    b.ToTable("DettagliProdotti");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.Newsletter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Attiva")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataIscrizione")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Newsletters");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.OpzioneProdotto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Disponibile")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Sovrapprezzo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OpzioniProdotti");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.Ordine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodiceOrdine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataOrdine")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModalitaRitiro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NoteOrdine")
                        .HasColumnType("TEXT");

                    b.Property<string>("Stato")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Totale")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("UtenteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CodiceOrdine")
                        .IsUnique();

                    b.HasIndex("UtenteId");

                    b.ToTable("Ordini");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.OrdineProdotto", b =>
                {
                    b.Property<int>("OrdineId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProdottoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OpzioniSelezionate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrezzoUnitario")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantita")
                        .HasColumnType("INTEGER");

                    b.HasKey("OrdineId", "ProdottoId");

                    b.HasIndex("ProdottoId");

                    b.ToTable("OrdiniProdotti");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.OtpVerifica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodiceOtp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Scadenza")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Utilizzato")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("OtpVerifiche");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.Pagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Importo")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetodoPagamento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrdineId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Stato")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrdineId")
                        .IsUnique();

                    b.ToTable("Pagamenti");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.Prenotazione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataPrenotazione")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroPersone")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NumeroTavolo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProdottoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Stato")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UtenteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProdottoId");

                    b.HasIndex("UtenteId");

                    b.ToTable("Prenotazioni");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.Prodotto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInserimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descrizione")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Disponibile")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImmagineUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Personalizzabile")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Prezzo")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantitaMagazzino")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Prodotti");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.ProdottoOpzione", b =>
                {
                    b.Property<int>("ProdottoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OpzioneProdottoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProdottoId", "OpzioneProdottoId");

                    b.HasIndex("OpzioneProdottoId");

                    b.ToTable("ProdottiOpzioni");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.Sconto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Attivo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataFine")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInizio")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Percentuale")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sconti");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.Scontrino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataEmissione")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroScontrino")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrdineId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PdfUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrdineId")
                        .IsUnique();

                    b.ToTable("Scontrini");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.Utente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataRegistrazione")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ruolo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Utenti");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.Carrello", b =>
                {
                    b.HasOne("OnlineShop.Data.Entities.Utente", "Utente")
                        .WithMany("Carrelli")
                        .HasForeignKey("UtenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.CarrelloProdotto", b =>
                {
                    b.HasOne("OnlineShop.Data.Entities.Carrello", "Carrello")
                        .WithMany("CarrelloProdotti")
                        .HasForeignKey("CarrelloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineShop.Data.Entities.Prodotto", "Prodotto")
                        .WithMany("CarrelloProdotti")
                        .HasForeignKey("ProdottoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrello");

                    b.Navigation("Prodotto");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.CarrelloProdottoOpzione", b =>
                {
                    b.HasOne("OnlineShop.Data.Entities.CarrelloProdotto", "CarrelloProdotto")
                        .WithMany("Opzioni")
                        .HasForeignKey("CarrelloProdottoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineShop.Data.Entities.OpzioneProdotto", "OpzioneProdotto")
                        .WithMany("CarrelloProdottoOpzioni")
                        .HasForeignKey("OpzioneProdottoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarrelloProdotto");

                    b.Navigation("OpzioneProdotto");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.DettaglioProdotto", b =>
                {
                    b.HasOne("OnlineShop.Data.Entities.Prodotto", "Prodotto")
                        .WithOne("DettaglioProdotto")
                        .HasForeignKey("OnlineShop.Data.Entities.DettaglioProdotto", "ProdottoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prodotto");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.Ordine", b =>
                {
                    b.HasOne("OnlineShop.Data.Entities.Utente", "Utente")
                        .WithMany("Ordini")
                        .HasForeignKey("UtenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.OrdineProdotto", b =>
                {
                    b.HasOne("OnlineShop.Data.Entities.Ordine", "Ordine")
                        .WithMany("OrdineProdotti")
                        .HasForeignKey("OrdineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineShop.Data.Entities.Prodotto", "Prodotto")
                        .WithMany("OrdineProdotti")
                        .HasForeignKey("ProdottoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ordine");

                    b.Navigation("Prodotto");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.Pagamento", b =>
                {
                    b.HasOne("OnlineShop.Data.Entities.Ordine", "Ordine")
                        .WithOne("Pagamento")
                        .HasForeignKey("OnlineShop.Data.Entities.Pagamento", "OrdineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ordine");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.Prenotazione", b =>
                {
                    b.HasOne("OnlineShop.Data.Entities.Prodotto", "Prodotto")
                        .WithMany("Prenotazioni")
                        .HasForeignKey("ProdottoId");

                    b.HasOne("OnlineShop.Data.Entities.Utente", "Utente")
                        .WithMany("Prenotazioni")
                        .HasForeignKey("UtenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prodotto");

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.ProdottoOpzione", b =>
                {
                    b.HasOne("OnlineShop.Data.Entities.OpzioneProdotto", "OpzioneProdotto")
                        .WithMany("ProdottiOpzioni")
                        .HasForeignKey("OpzioneProdottoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineShop.Data.Entities.Prodotto", "Prodotto")
                        .WithMany("ProdottiOpzioni")
                        .HasForeignKey("ProdottoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OpzioneProdotto");

                    b.Navigation("Prodotto");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.Scontrino", b =>
                {
                    b.HasOne("OnlineShop.Data.Entities.Ordine", "Ordine")
                        .WithOne("Scontrino")
                        .HasForeignKey("OnlineShop.Data.Entities.Scontrino", "OrdineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ordine");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.Carrello", b =>
                {
                    b.Navigation("CarrelloProdotti");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.CarrelloProdotto", b =>
                {
                    b.Navigation("Opzioni");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.OpzioneProdotto", b =>
                {
                    b.Navigation("CarrelloProdottoOpzioni");

                    b.Navigation("ProdottiOpzioni");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.Ordine", b =>
                {
                    b.Navigation("OrdineProdotti");

                    b.Navigation("Pagamento");

                    b.Navigation("Scontrino");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.Prodotto", b =>
                {
                    b.Navigation("CarrelloProdotti");

                    b.Navigation("DettaglioProdotto");

                    b.Navigation("OrdineProdotti");

                    b.Navigation("Prenotazioni");

                    b.Navigation("ProdottiOpzioni");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.Utente", b =>
                {
                    b.Navigation("Carrelli");

                    b.Navigation("Ordini");

                    b.Navigation("Prenotazioni");
                });
#pragma warning restore 612, 618
        }
    }
}
