// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace OnlineShop.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260725174946_InitialCreate2")]
    partial class InitialCreate2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("OnlineShop.Data.Entities.Carrello", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("TEXT");

                    b.Property<int>("UtenteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UtenteId");

                    b.ToTable("Carrelli");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.CarrelloProdotto", b =>
                {
                    b.Property<int>("CarrelloId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProdottoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantita")
                        .HasColumnType("INTEGER");

                    b.HasKey("CarrelloId", "ProdottoId");

                    b.HasIndex("ProdottoId");

                    b.ToTable("CarrelloProdotti");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.DatiFatturazione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cap")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Citta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodiceDestinatario")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodiceFiscale")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Indirizzo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nazione")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrdineId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PartitaIva")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pec")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RagioneSociale")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrdineId")
                        .IsUnique();

                    b.ToTable("DatiFatturazioni");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.Fattura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataEmissione")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Imponibile")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Iva")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroFattura")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrdineId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PdfUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Stato")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Totale")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrdineId")
                        .IsUnique();

                    b.ToTable("Fatture");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.FatturaDettaglio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FatturaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("IvaPercentuale")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrezzoUnitario")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantita")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FatturaId");

                    b.ToTable("FattureDettagli");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.Newsletter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Attiva")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataIscrizione")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Newsletters");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.Ordine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataOrdine")
                        .HasColumnType("TEXT");

                    b.Property<string>("Stato")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Totale")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("UtenteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UtenteId");

                    b.ToTable("Ordini");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.OrdineProdotto", b =>
                {
                    b.Property<int>("OrdineId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProdottoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrezzoUnitario")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantita")
                        .HasColumnType("INTEGER");

                    b.HasKey("OrdineId", "ProdottoId");

                    b.HasIndex("ProdottoId");

                    b.ToTable("OrdiniProdotti");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.OtpVerifica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodiceOtp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Scadenza")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Utilizzato")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("OtpVerifiche");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.Pagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Importo")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetodoPagamento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrdineId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Stato")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrdineId")
                        .IsUnique();

                    b.ToTable("Pagamenti");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.Prenotazione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataPrenotazione")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProdottoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Stato")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UtenteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProdottoId");

                    b.HasIndex("UtenteId");

                    b.ToTable("Prenotazioni");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.Prodotto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInserimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descrizione")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Disponibile")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImmagineUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Prezzo")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantitaMagazzino")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Prodotti");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.Sconto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Attivo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataFine")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInizio")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Percentuale")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sconti");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.Scontrino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataEmissione")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroScontrino")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrdineId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PdfUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrdineId")
                        .IsUnique();

                    b.ToTable("Scontrini");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.Utente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataRegistrazione")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ruolo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Utenti");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.Carrello", b =>
                {
                    b.HasOne("OnlineShop.Data.Entities.Utente", "Utente")
                        .WithMany("Carrelli")
                        .HasForeignKey("UtenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.CarrelloProdotto", b =>
                {
                    b.HasOne("OnlineShop.Data.Entities.Carrello", "Carrello")
                        .WithMany("CarrelloProdotti")
                        .HasForeignKey("CarrelloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineShop.Data.Entities.Prodotto", "Prodotto")
                        .WithMany("CarrelloProdotti")
                        .HasForeignKey("ProdottoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrello");

                    b.Navigation("Prodotto");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.DatiFatturazione", b =>
                {
                    b.HasOne("OnlineShop.Data.Entities.Ordine", "Ordine")
                        .WithOne("DatiFatturazione")
                        .HasForeignKey("OnlineShop.Data.Entities.DatiFatturazione", "OrdineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ordine");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.Fattura", b =>
                {
                    b.HasOne("OnlineShop.Data.Entities.Ordine", "Ordine")
                        .WithOne("Fattura")
                        .HasForeignKey("OnlineShop.Data.Entities.Fattura", "OrdineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ordine");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.FatturaDettaglio", b =>
                {
                    b.HasOne("OnlineShop.Data.Entities.Fattura", "Fattura")
                        .WithMany("FatturaDettagli")
                        .HasForeignKey("FatturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fattura");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.Ordine", b =>
                {
                    b.HasOne("OnlineShop.Data.Entities.Utente", "Utente")
                        .WithMany("Ordini")
                        .HasForeignKey("UtenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.OrdineProdotto", b =>
                {
                    b.HasOne("OnlineShop.Data.Entities.Ordine", "Ordine")
                        .WithMany("OrdineProdotti")
                        .HasForeignKey("OrdineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineShop.Data.Entities.Prodotto", "Prodotto")
                        .WithMany("OrdineProdotti")
                        .HasForeignKey("ProdottoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ordine");

                    b.Navigation("Prodotto");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.Pagamento", b =>
                {
                    b.HasOne("OnlineShop.Data.Entities.Ordine", "Ordine")
                        .WithOne("Pagamento")
                        .HasForeignKey("OnlineShop.Data.Entities.Pagamento", "OrdineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ordine");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.Prenotazione", b =>
                {
                    b.HasOne("OnlineShop.Data.Entities.Prodotto", "Prodotto")
                        .WithMany("Prenotazioni")
                        .HasForeignKey("ProdottoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineShop.Data.Entities.Utente", "Utente")
                        .WithMany("Prenotazioni")
                        .HasForeignKey("UtenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prodotto");

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.Scontrino", b =>
                {
                    b.HasOne("OnlineShop.Data.Entities.Ordine", "Ordine")
                        .WithOne("Scontrino")
                        .HasForeignKey("OnlineShop.Data.Entities.Scontrino", "OrdineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ordine");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.Carrello", b =>
                {
                    b.Navigation("CarrelloProdotti");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.Fattura", b =>
                {
                    b.Navigation("FatturaDettagli");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.Ordine", b =>
                {
                    b.Navigation("DatiFatturazione");

                    b.Navigation("Fattura");

                    b.Navigation("OrdineProdotti");

                    b.Navigation("Pagamento");

                    b.Navigation("Scontrino");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.Prodotto", b =>
                {
                    b.Navigation("CarrelloProdotti");

                    b.Navigation("OrdineProdotti");

                    b.Navigation("Prenotazioni");
                });

            modelBuilder.Entity("OnlineShop.Data.Entities.Utente", b =>
                {
                    b.Navigation("Carrelli");

                    b.Navigation("Ordini");

                    b.Navigation("Prenotazioni");
                });
#pragma warning restore 612, 618
        }
    }
}
